### ISSUE TITLE
Add translation for substring_index()

### ISSUE THREAD

**Issue by ianmcook** [ianmcook/queryparser#29]
Add a translation for the MySQL function [`substring_index()`](https://dev.mysql.com/doc/refman/8.0/en/string-functions.html#function_substring-index) as requested by @jimmyg3g in https://github.com/ianmcook/tidyquery/issues/13

**Comment by ianmcook** [comment]
Translation for `tidyverse = TRUE` added in https://github.com/ianmcook/queryparser/commit/f984e897ca5b1f7691644cb641d5f0c2be928425

**Comment by ianmcook** [comment]
Tests for when `tidyverse = TRUE` added in https://github.com/ianmcook/queryparser/commit/db8bc7ec9734409a61368efaa33f66f27f21255a

**Comment by ianmcook** [comment]
Fixed a bug in https://github.com/ianmcook/queryparser/commit/96e62ab9e7f3b764a5dcc26831e65942995523b7

**Comment by ianmcook** [comment]
I'm not going to implement a translation for when `tidyverse = FALSE` right now because it's complicated by the lack of a string reverse function in base R.

**Comment by ianmcook** [comment]
@jimmyg3g if you install queryparser from GitHub, then restart R and load tidyquery, you should be able to run queries that use the `substring_index()` function. Let me know if this works for you! The command to install it from GitHub is:
```r
devtools::install_github("ianmcook/queryparser")
```
I'll submit to CRAN along with some other changes sometime in the next few months.

**Comment by jimmyg3g** [comment]
@ianmcook Thanks, it's working for me. Thanks for sharing the link to it code too, fascinating to see how it works behind the scenes!
